export const FEATURE_SEARCH_REGISTRY = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Your control center for event progress, status, and quick actions.',
    path: '/',
    quickAction: { label: 'Open Dashboard', path: '/' },
    category: 'feature',
    priority: 100,
    keywords: ['home', 'overview', 'status', 'activity'],
  },
  {
    id: 'how-it-works',
    title: 'How It Works',
    description: 'The guided map of the full IMC workflow from intake to reporting.',
    path: '/workflow',
    quickAction: { label: 'Open Guide', path: '/workflow' },
    category: 'feature',
    priority: 98,
    keywords: ['guide', 'workflow', 'steps', 'process', 'user guide'],
  },
  {
    id: 'white-papers',
    title: 'White Papers',
    description: 'Long-form strategy and architecture papers for operations, risk, and compliance stakeholders.',
    path: '/white-papers',
    quickAction: { label: 'Open White Papers', path: '/white-papers' },
    category: 'feature',
    priority: 97,
    keywords: ['white paper', 'strategy', 'architecture', 'risk', 'compliance', 'stakeholder'],
  },
  {
    id: 'user-guide',
    title: 'User Guide',
    description: 'Step-by-step operating guide with practical instructions by module.',
    path: '/user-guide',
    quickAction: { label: 'Open User Guide', path: '/user-guide' },
    category: 'feature',
    priority: 96,
    keywords: ['manual', 'help', 'instructions', 'guide', 'training'],
  },
  {
    id: 'start-event',
    title: 'Start Event',
    description: 'Create a new event with AI intake and production-ready defaults.',
    path: '/events/create',
    quickAction: { label: 'Create Event', path: '/events/create' },
    category: 'feature',
    priority: 95,
    keywords: ['new event', 'create event', 'intake', 'event form'],
  },
  {
    id: 'ai-intake',
    title: 'AI Intake (Voice + Email + Upload)',
    description: 'Speak, paste, or upload to auto-fill contacts, venues, and event drafts.',
    path: '/events/create?ai=intake',
    quickAction: { label: 'Open AI Intake', path: '/events/create?ai=intake' },
    category: 'feature',
    priority: 94,
    keywords: ['voice', 'email intake', 'ocr', 'autofill', 'upload'],
  },
  {
    id: 'imc-composer',
    title: 'IMC Composer',
    description: 'Generate and distribute social, press, and calendar content.',
    path: '/imc-composer',
    quickAction: { label: 'Open Composer', path: '/imc-composer' },
    category: 'feature',
    priority: 93,
    keywords: ['composer', 'distribution', 'social posts', 'press release', 'calendar'],
  },
  {
    id: 'production-ops',
    title: 'Production Ops Hub',
    description: 'Manage staffing, checklists, inventory, contracts, and operations.',
    path: '/production-ops',
    quickAction: { label: 'Open Production Ops', path: '/production-ops' },
    category: 'feature',
    priority: 92,
    keywords: ['production', 'operations', 'staffing', 'inventory', 'contracts'],
  },
  {
    id: 'plots-layouts',
    title: 'Plots & Layouts',
    description: 'Build stage and venue layouts with technical overlays and exports.',
    path: '/production-ops/event-ops?focus=event_ops',
    quickAction: { label: 'Open Plots & Layouts', path: '/production-ops/event-ops?focus=event_ops' },
    category: 'feature',
    priority: 91,
    keywords: ['stage plot', 'layout', 'lighting plot', 'sound plot', 'zones'],
  },
  {
    id: 'timeline-editor',
    title: 'Timeline Editor',
    description: 'Coordinate cues across run of show, lighting, sound, and projection.',
    path: '/run-of-show',
    quickAction: { label: 'Open Timeline', path: '/run-of-show' },
    category: 'feature',
    priority: 90,
    keywords: ['timeline', 'cues', 'run of show', 'lx', 'snd', 'projection'],
  },
  {
    id: 'safety-risk',
    title: 'Safety & Risk',
    description: 'Track permits, insurance, incident logs, and emergency planning.',
    path: '/safety-risk',
    quickAction: { label: 'Open Safety & Risk', path: '/safety-risk' },
    category: 'feature',
    priority: 89,
    keywords: ['safety', 'risk', 'permits', 'insurance', 'emergency action plan'],
  },
  {
    id: 'production-calendar',
    title: 'Rehearsal Calendar',
    description: 'Schedule rehearsals and calls, assign teams, and sync to Google Calendar.',
    path: '/production-calendar',
    quickAction: { label: 'Open Calendar', path: '/production-calendar' },
    category: 'feature',
    priority: 88,
    keywords: ['calendar', 'rehearsal', 'calls', 'google calendar', 'schedule'],
  },
  {
    id: 'chat-dashboard',
    title: 'Chat Dashboard',
    description: 'Browse all user chats by recency, alphabetical order, and favorites.',
    path: '/chat',
    quickAction: { label: 'Open Chats', path: '/chat' },
    category: 'feature',
    priority: 87,
    keywords: ['chat', 'messages', 'group chat', 'favorites', 'threads'],
  },
  {
    id: 'catbot-buddy',
    title: 'CatBot Buddy',
    description: 'Ask for routing, quick answers, and step-by-step help.',
    path: '/buddy',
    quickAction: { label: 'Open CatBot Buddy', path: '/buddy' },
    category: 'feature',
    priority: 86,
    keywords: ['buddy', 'catbot', 'assistant', 'help'],
  },
  {
    id: 'press-page',
    title: 'Press Page Generator',
    description: 'Build a shareable press page with links, exports, and media-ready copy.',
    path: '/press-page/new',
    quickAction: { label: 'Create Press Page', path: '/press-page/new' },
    category: 'feature',
    priority: 85,
    keywords: ['press page', 'press kit', 'media page', 'share link', 'pdf'],
  },
  {
    id: 'capture-hub',
    title: 'Capture Hub',
    description: 'Manage podcast and media capture workflows for Zoom and YouTube.',
    path: '/podcast',
    quickAction: { label: 'Open Capture Hub', path: '/podcast' },
    category: 'feature',
    priority: 84,
    keywords: ['capture', 'podcast', 'zoom', 'youtube', 'media'],
  },
  {
    id: 'crew-portal',
    title: 'Crew Portal',
    description: 'Manage crew profiles, assignments, and operations readiness.',
    path: '/crew',
    quickAction: { label: 'Open Crew Portal', path: '/crew' },
    category: 'feature',
    priority: 83,
    keywords: ['crew', 'staff', 'assignments', 'team', 'roles'],
  },
  {
    id: 'venue-setup',
    title: 'Venue Setup',
    description: 'Configure reusable venue profiles, zones, and defaults.',
    path: '/venue-setup',
    quickAction: { label: 'Open Venue Setup', path: '/venue-setup' },
    category: 'feature',
    priority: 82,
    keywords: ['venue', 'spaces', 'zones', 'address', 'profile'],
  },
  {
    id: 'artist-setup',
    title: 'Artist Setup',
    description: 'Manage artist profiles, bios, media, and reusable assets.',
    path: '/artist-setup',
    quickAction: { label: 'Open Artist Setup', path: '/artist-setup' },
    category: 'feature',
    priority: 81,
    keywords: ['artist', 'bio', 'band', 'acts', 'profile'],
  },
  {
    id: 'media-gallery',
    title: 'Media Gallery',
    description: 'Store and download formatted image assets by event and channel.',
    path: '/media',
    quickAction: { label: 'Open Media Gallery', path: '/media' },
    category: 'feature',
    priority: 80,
    keywords: ['images', 'assets', 'gallery', 'downloads', 'formats'],
  },
  {
    id: 'campaign-tracker',
    title: 'Campaign Tracker',
    description: 'Review distribution status and campaign completion records.',
    path: '/campaigns',
    quickAction: { label: 'Open Campaign Tracker', path: '/campaigns' },
    category: 'feature',
    priority: 79,
    keywords: ['campaigns', 'tracking', 'status', 'distribution records'],
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Configure integrations, preferences, and account controls.',
    path: '/settings',
    quickAction: { label: 'Open Settings', path: '/settings' },
    category: 'feature',
    priority: 78,
    keywords: ['settings', 'integrations', 'preferences', 'oauth'],
  },
];

export const FEATURE_SEARCH_SCOPE_OPTIONS = [
  { value: 'all', label: 'All Accessible' },
  { value: 'org', label: 'This Organization' },
  { value: 'venue', label: 'This Venue' },
  { value: 'event', label: 'This Event' },
];

export const FEATURE_SEARCH_CATEGORY_OPTIONS = [
  { value: 'all', label: 'All Categories' },
  { value: 'features', label: 'Features' },
  { value: 'events', label: 'Events' },
  { value: 'venues', label: 'Venues' },
  { value: 'plots', label: 'Plots' },
  { value: 'cues', label: 'Cues' },
  { value: 'calendar', label: 'Calendar' },
  { value: 'documents', label: 'Documents' },
  { value: 'permits_insurance', label: 'Permits/Insurance' },
  { value: 'checklists', label: 'Checklists' },
  { value: 'people', label: 'People' },
];
